config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'avacado/index'

  resources :prospects
  get 'welcome/index'
  root 'welcome#index'
  get 'welcome/show'
  root 'welcome#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/prospect.rb
class Prospect < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/avacado_controller.rb
class AvacadoController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.fetch(:comment, {})
    end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :set_prospect, only: [:show, :edit, :update, :destroy]

  # GET /prospects
  # GET /prospects.json
  def index
    @prospects = Prospect.all
  end

  # GET /prospects/1
  # GET /prospects/1.json
  def show
  end

  # GET /prospects/new
  def new
    @prospect = Prospect.new
  end

  # GET /prospects/1/edit
  def edit
  end

  # POST /prospects
  # POST /prospects.json
  def create
    @prospect = Prospect.new(prospect_params)

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to @prospect, notice: 'Prospect was successfully created.' }
        format.json { render :show, status: :created, location: @prospect }
      else
        format.html { render :new }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospects/1
  # PATCH/PUT /prospects/1.json
  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to @prospect, notice: 'Prospect was successfully updated.' }
        format.json { render :show, status: :ok, location: @prospect }
      else
        format.html { render :edit }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1
  # DELETE /prospects/1.json
  def destroy
    @prospect.destroy
    respond_to do |format|
      format.html { redirect_to prospects_url, notice: 'Prospect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prospect_params
      params.fetch(:prospect, {})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avacado_helper.rb
module AvacadoHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/avacado/index.html.erb
<h1>Avacado#index</h1>


<!-- Begin Nav -->
  <nav class="top-bar topbar-responsive">
    <div class="top-bar-title">
      <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
        <button class="menu-icon" type="button" data-toggle></button>
      </span>
      <a class="topbar-responsive-logo" href="about.html"><strong>Cars</strong></a>
    </div>
    <div id="topbar-responsive" class="topbar-responsive-links">
      <div class="top-bar-right">
        <ul class="menu simple vertical medium-horizontal">
          <li><a href="site.html">Home</a></li>
          <li><a href="about.html">About</a></li>
          <li><a href="services.html">Services</a></li>
          <li><a href="works.html">Works</a></li>
          <li><a href="newcars.html">New Cars</a></li>
          <li><a href="contact.html">Contact</a></li>
          <li>
            <button type="button" class="button hollow topbar-responsive-button">Categories</button>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Small Nav -->

  <!-- Begin Hero -->
  <div class="marketing-site-hero">
  <div class="marketing-site-hero-content">
    <h1>Contact US</h1>
    <p class="subheader">Our team has you covered.</p>
      <img src="http://farm8.static.flickr.com/7056/26867933430_33962f6441.jpg" alt="" />
      <a href="newcars.html" class="round button">See our range of beauties </a>
  </div>
</div>

  <!-- Small Hero -->

  <!-- Begin Content -->
  <section class="filter-simple">
  <div class="button-group round">
    <button class="button hollow filter-simple-button is-active" data-filter="all"><a href="site.html">Me</button>
    <button class="button hollow filter-simple-button" data-filter="space"><a href="newcars.html">Soul</button>
    <button class="button hollow filter-simple-button" data-filter="cats"><a href="works.html">Cars</button>
    <button class="button hollow filter-simple-button" data-filter="murray"><a href="about.html">Pew</button>
  </div>

  <div class="row small-up-2 medium-up-3 large-up-4">
    <div class="column column-block filter-simple-item space">
      <img src="https://drivetribe.imgix.net/QjvNpfb6SVyI_J0VXxU5qA?w=600&h=600&fm=pjpg&auto=compress&fit=crop&crop=faces,edges" alt="" />
    </div>
    <div class="column column-block filter-simple-item murray">
      <img src="https://s-media-cache-ak0.pinimg.com/736x/d2/6d/92/d26d927df29b746f5f2131c07c1cde4a.jpg" alt="" />
    </div>
    <div class="column column-block filter-simple-item cats">
      <img src="https://s-media-cache-ak0.pinimg.com/736x/21/23/ab/2123ab0650b32b791ba73797dbf450dc.jpg" alt="" />
    </div>
    <div class="column column-block filter-simple-item cats">
      <img src="https://pbs.twimg.com/media/DVEoUPCXcAEHUPo.jpg" alt="" />
    </div>
    <div class="column column-block filter-simple-item cats">
      <img src="https://pbs.twimg.com/media/B7k7jv_IMAAYalV.jpg" alt="" />
    </div>
    <div class="column column-block filter-simple-item murray">
      <img src="https://scontent-ort2-1.cdninstagram.com/vp/7f0796252b69eca69886bdb427b01b2c/5B65056C/t51.2885-15/s480x480/e35/c236.0.607.607/28157547_1749283241804680_7007092959917113344_n.jpg" alt="" />
    </div>
    <div class="column column-block filter-simple-item murray">
      <img src="https://i.pinimg.com/736x/42/2b/fe/422bfea72e78b5958d88057add176ec5.jpg" alt="" />
    </div>
    <div class="column column-block filter-simple-item cats">
      <img src="https://78.media.tumblr.com/d14cad97e7bb8969dba836479c4e17bf/tumblr_o7gr4zWDcF1u73hheo1_500.jpg" alt="" />
    </div>
    <div class="column column-block filter-simple-item murray">
      <img src="https://i.pinimg.com/564x/89/d9/a3/89d9a3ae70406597d319fe30caddd495--luxury-auto-black-cars.jpg" alt="" />
    </div>
    <div class="column column-block filter-simple-item cats">
      <img src="http://78.media.tumblr.com/eccac0786f41985601ad27296b16a5ca/tumblr_my9f22eDgr1rrt0gmo1_500.jpg" alt="" />
    </div>
    <div class="column column-block filter-simple-item space">
      <img src="https://i.pinimg.com/originals/48/84/be/4884bee0ff4e6a53cef4fdead91d304f.jpg" alt="" />
    </div>
    <div class="column column-block filter-simple-item space">
      <img src="https://i.pinimg.com/originals/dc/42/9c/dc429c060cbc8a6fd1fa68e1f98a8dc9.jpg" alt="" />
    </div>
  </div>
</section>


  <!-- Small Content -->

  <!-- Begin Footer -->
  <!-- with icon font (fontawesome) -->
  <div class="blogpost-footer-actions">
    <div class="blogpost-footer-actions-left">
      <a href="#"><i class="fa fa-heart-o" aria-hidden="true"> Cars Are Life</i></a>
      <a href="#"><i class="fa fa-comment-o" aria-hidden="true"> Cars Do Come True</i></a>
    </div>
    <div class="blogpost-footer-actions-right">
      <a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a>
      <a href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
    </div>
  </div>

  <div class="blogpost-footer-author-section">

    <div>
      <a href="#" class="blogpost-footer-author">
        <img class="avatar" src="https://lh3.googleusercontent.com/-3dOJPVX8VAw/WEYbPmhOpkI/AAAAAAAAAYs/fD4CDrluChQZ5Jl9M7kwq9XsrMqD_-jTQCEw/w139-h140-p/86B083FE-D78E-4AF9-B7E7-BD2156BFD496.JPG" alt="" />
        <div>
          <p class="author">Bushra Hussain</p>
          <p class="bio">She is the owner of this lovely shop. A girl can do cars too. </p>
        </div>
      </a>
    </div>
    <a href="#" class="hollow button success">Follow</a>

  </div>



  <!-- Small Footer -->

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Bushra's Website" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/prospects/_form.html.erb
<%= form_with(model: prospect, local: true) do |form| %>
  <% if prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
      <% prospect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prospects/edit.html.erb
<h1>Editing Prospect</h1>

<%= render 'form', prospect: @prospect %>

<%= link_to 'Show', @prospect %> |
<%= link_to 'Back', prospects_path %>

app/views/prospects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prospects</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each do |prospect| %>
      <tr>
        <td><%= link_to 'Show', prospect %></td>
        <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
        <td><%= link_to 'Destroy', prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prospect', new_prospect_path %>

app/views/prospects/new.html.erb
<h1>New Prospect</h1>

<%= render 'form', prospect: @prospect %>

<%= link_to 'Back', prospects_path %>

app/views/prospects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_prospect_path(@prospect) %> |
<%= link_to 'Back', prospects_path %>

app/views/welcome/index.html.erb
<!-- Begin Nav -->
<nav class="top-bar topbar-responsive">
  <div class="top-bar-title">
    <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
    </span>
    <a class="topbar-responsive-logo" href="newcars.html"><strong>Cars</strong></a>
  </div>
  <div id="topbar-responsive" class="topbar-responsive-links">
    <div class="top-bar-right">
      <ul class="menu simple vertical medium-horizontal">
        <li><a href="show.html.erb">Home</a></li>
        <li><a href="show.html.erb">About</a></li>
        <li><a href="show.html.erb">Services</a></li>
        <li><a href="works.html">Works</a></li>
        <li><a href="show.html.erb">New Cars</a></li>
        <li><a href="cshow.html.erb">Contact</a></li>
        <li>
          <button type="button" class="button hollow topbar-responsive-button">Categories</button>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!-- Small Nav -->

<!-- Begin Hero -->
<div class="neat-article-container">
  <div class="row large-8 columns align-center">
    <div class="neat-article-header">
      <div class="article-header-avatar">
        <img class="header-avatar" src="https://lh3.googleusercontent.com/-tJUdZkFGZDU/WuiNmC7FNnI/AAAAAAAAAdM/NCiUSSZm9jwsljZe5rnoLlK83gFmDvI6gCEwYBhgL/w138-h140-p/unnamed%2B%25281%2529.jpg">
      </div>
      <div class="article-header-author">
        <p class="author-name">
          Bushra S. Hussain
        </p>
        <p class="author-description">
          Car girl who has all the cars in her hands.
        </p>
        <p class="article-date-read">My Fav Car At The Moment</p>
      </div>
    </div>
    <div class="neat-article-title">
      <h3 class="article-title">
        Nissan GT-R
      </h3>
    </div>
  </div>
  <div class="neat-article-image">
    <img class="article-image" src="http://i.sxdrv.com/images/56dd96fd966d0.jpg" alt="Space">
  </div>
  <div class="row neat-article-content">
    <div class="small-2 large-2 columns" data-sticky-container>
      <div class="sticky article-social" data-sticky data-anchor="sticky1" data-sticky-on="small">
        <div class="rounded-social-buttons">
          <a class="social-button facebook" href="show.html.erb"></a>
          <a class="social-button twitter" href="contact.html"></a>
          <a class="social-button google-plus" href="site.html"></a>
        </div>
      </div>
    </div>
    <div class="small-10 large-8 columns" id="sticky1">
      <div class="article-content">
        <p>
          Doesn’t matter what you call it—GT-R or, more fittingly, Godzilla—Nissan’s range topper is a supercar-stomping, high-tech dynamo. Its 3.8-liter twin-turbo V-6 makes a mighty 565 hp while a six-speed dual-clutch automatic and all-wheel drive team up to put all that power to the pavement. The GT-R’s quick steering, rigid structure and adjustable suspension can make even amateurs feel positively heroic from behind the wheel. Want more? Check out the track-ready NISMO-tuned variant with 600 hp.
        </p>
        <p>
          From start to finish, each GT-R engine is handcrafted by its own master engine-builder in a climate-controlled "clean room." Each twin-turbo V6 is precisely assembled from lightweight, highly durable aluminum and magnesium parts.
        </p>
        <p>
          Add a touch of premium with these ultimate floor mats that feature a metal GT-R logo and carbon-fiber inserts.
        </p>
        <p>
           It takes the exacting standards of the planet's most talented and devoted engine builders to produce the engine that has redefined what a supercar can be. NISMO-tuned suspension gains force with Bilstein® DampTronic® components that use computerized control to continually adjust shock absorber damping. The system has three driver-selectable driving modes and constantly monitors vehicle speed, lateral acceleration, torque, engine rpm and braking behavior to help provide the ideal ride/handling balance. To match the precision of the other GT-R suspension components, high-accuracy progressive-rate springs were developed and manufactured to extremely high tolerances.
        </p>
          Once again the 2017 GT-R raises the bar for ultimate performance. Inside, the GT-R takes a giant step forward with a new design that reduces driver workload, while stepping up to a new level of premium with hand-selected and handcrafted materials. Add in greater power, and a suspension retuned to provide a more supple ride while enhancing handling, and Legendary Exhilaration has never looked better.Most stability control systems cut engine power or apply the brakes when they sense a loss of control. That's fine for the road, but slow going in competition conditions. While cornering with the advanced Vehicle Dynamic Control (VDC) system in R-Mode, it actually sends more power to the appropriate wheels when it senses oversteer or understeer, helping to keep it on the steered course, a much quicker way to go in track conditions.
        <p>
          The GT-R 6-speed sequential dual-clutch transmission shifts as quickly as 0.15 seconds when in R-Mode.Inside are separate clutches for the odd and even gears. When in an odd-numbered gear, the adjacent even-numbered gear is “pre-selected,” ready to make the shift immediately. Then, to achieve ideal front-to-rear weight distribution, the GT-R clutches, transmission and transfer case are mounted in the rear of the chassis, creating the world’s first independent rear transaxle for an All-Wheel Drive vehicle.
        </p>
        <p>
          Awe-inducing. 600 horsepower of fury combined with unmatched control. Building on the advanced technology of the hand-assembled GT-R engine, GT-R NISMO adds high-capacity turbos developed from our GT3 racing program.The result is performance that's as stunning on the road as it is dominating on the track.
        </p>
      </div>
    </div>
  </div>

</div>




<!-- Small Hero -->

<!-- Begin Content -->
<div class="news-image-gallery-container">
  <div class="row">
    <div class="small-12 medium-12 large-8 columns">
      <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit data-options="animInFromLeft:fade-in; animInFromRight:fade-in; animOutToLeft:fade-out; animOutToRight:fade-out;">
        <ul class="orbit-container">
          <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
          <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
          <li class="is-active orbit-slide">
            <img class="orbit-image" src="https://s-media-cache-ak0.pinimg.com/736x/ed/5f/c2/ed5fc2ae11b7f3ea9f40e71972c9ca9c.jpg" alt="Space">
            <figcaption class="orbit-caption">Look at these stanced out cars.</figcaption>
          </li>
          <li class="orbit-slide">
            <img class="orbit-image" src="http://www.mrwallpaper.com/wallpapers/nissan-gtr-wide-body-2560x1600.jpg" alt="Space">
            <figcaption class="orbit-caption">Lets Rocket With This Awesome Z.</figcaption>
          </li>
          <li class="orbit-slide">
            <img class="orbit-image" src="https://shop.yasiddesign.com/wp-content/uploads/2015/08/A3-Toyota-Supra-11.jpg" alt="Space">
            <figcaption class="orbit-caption">Encapsulating</figcaption>
          </li>
          <li class="orbit-slide">
            <img class="orbit-image" src="https://media.ed.edmunds-media.com/bmw/m6-gran-coupe/2017/ot/2017_bmw_m6-gran-coupe_LIFE1_ot_1130165_1280.jpg" alt="Space">
            <figcaption class="orbit-caption">Outta This World</figcaption>
          </li>
        </ul>
        <nav class="orbit-bullets">
          <button class="is-active" data-slide="0"><span class="show-for-sr">First slide details.</span><span class="show-for-sr">Current Slide</span></button>
          <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
          <button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
          <button data-slide="3"><span class="show-for-sr">Fourth slide details.</span></button>
        </nav>
      </div>
    </div>
    <div class="small-12 medium-12 large-4 columns">
      <div class="rounded-social-buttons">
        <a class="social-button facebook" href="#"></a>
        <a class="social-button twitter" href="#"></a>
        <a class="social-button linkedin" href="#"></a>
        <a class="social-button google-plus" href="#"></a>
      </div>
      <div class="clearfix"></div>
      <h4 class="news-image-gallery-title">Pew PEW</h4>
      <p>
        Cars
        <a href="site.html" class="read-more">
          Read More
        </a>
      </p>
    </div>
  </div>
</div>


<!-- Small Content -->

<!-- Begin Footer -->
<!-- with icon font (fontawesome) -->
<div class="blogpost-footer-actions">
  <div class="blogpost-footer-actions-left">
    <a href="#"><i class="fa fa-heart-o" aria-hidden="true"> Cars Are Life</i></a>
    <a href="#"><i class="fa fa-comment-o" aria-hidden="true"> Cars Do Come True</i></a>
  </div>
  <div class="blogpost-footer-actions-right">
    <a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a>
    <a href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
  </div>
</div>

<div class="blogpost-footer-author-section">

  <div>
    <a href="#" class="blogpost-footer-author">
      <img class="avatar" src="https://lh3.googleusercontent.com/-3dOJPVX8VAw/WEYbPmhOpkI/AAAAAAAAAYs/fD4CDrluChQZ5Jl9M7kwq9XsrMqD_-jTQCEw/w139-h140-p/86B083FE-D78E-4AF9-B7E7-BD2156BFD496.JPG" alt="" />
      <div>
        <p class="author">Bushra Hussain</p>
        <p class="bio">She is the owner of this lovely shop. A girl can do cars too. </p>
      </div>
    </a>
  </div>
  <a href="#" class="hollow button success">Follow</a>

</div>



<!-- Small Footer -->